# Generated by Django 5.0 on 2023-12-13 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_alter_habit_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='linked_habit',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='habits.habit', verbose_name='связанная привычка'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='reward',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='награда'),
        ),
    ]
