# Generated by Django 4.2.8 on 2023-12-20 16:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0006_alter_habit_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
